### ISSUE TITLE
getting this error, please help

### ISSUE THREAD

**Issue by RYG81** [dfl/comfyui-tcd-scheduler#5]
Error occurred when executing TCDScheduler:

module 'comfy.samplers' has no attribute 'calculate_sigmas_scheduler'

File "D:\000AI\00ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\comfyui-tcd-scheduler\sampler_tcd.py", line 133, in get_sigmas
sigmas = comfy.samplers.calculate_sigmas_scheduler(model.model, "ddim_uniform", steps).cpu()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by bvolkmer** [comment]
I added a pull request. This is due to a ComfyUI change: comfyanonymous/ComfyUI@1a0486b

**Comment by RYG81** [comment]
i have latest update for comfy but still not working. hope to have it working back soon.

**Comment by dfl** [comment]
@RYG81 I cannot reproduce your issue. The latest update for comfy created the error, but #6 fixes it. Please make sure you have updated the comfyui-tcd-scheduler node.

**Comment by RYG81** [comment]
yes updated again tonight and its working now
