### ISSUE TITLE
TCD Scheduler is missing a denoising adjustment slider, which makes it impossible to control the redrawing amplitude in video remapping and image-to-image generation.

### ISSUE THREAD

**Issue by hahy36** [dfl/comfyui-tcd-scheduler#7]

**Comment by dfl** [comment]
Scheduler only gives timing info, it’s the sampler that is responsible for dealing with noise injection. I have not yet figured out how to do img2img with custom sampler in ComfyUI, it’s a bit complicated.

**Comment by dfl** [comment]
Because the native KSampler does not have a way to support the extra Gamma parameter that TCD requires, it cannot be built in. Maybe you can ask @comfyanonymous about it.
